# **BASIC STATISTICS-2**

In [ ]:
#Problem Statement : Hospital Patient Data Analysis
#Context: A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info
#         and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

In [ ]:
#Tasks:
#           1.	Load the patient dataset and show summary with info().
#           2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
#           3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
#           4.	Use groupby to find total bill amount per department.
#           5.	Remove duplicate patient records based on PatientID.
#           6.	Fill missing BillAmount values with the mean bill amount.
#           7.	Merge the billing dataset with patient dataset on PatientID.
#           8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
#           9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [20]:
import pandas as pd
import numpy as np
df_original_patient = pd.read_csv('/content/Patient_Data.csv')
df_original_billing = pd.read_csv('/content/Billing_Data.csv')

In [21]:
df_original_patient.shape

(6, 7)

In [22]:
df_original_patient.head(10)

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [31]:
df_original_billing.head(10)

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [23]:
df_original_patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [24]:
#2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
df = df_original_patient[['PatientID','Department','Doctor','BillAmount']]
df #select the columns which is mentioned

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [10]:
# 4.	Use groupby to find total bill amount per department.
total_bill_per_dept = df.groupby('Department')['BillAmount'].sum()
print('Total bill amount per department:',total_bill_per_dept)

Total bill amount per department: Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [27]:
# 5.	Remove duplicate patient records based on PatientID.
df_unique = df.drop_duplicates(subset='PatientID',keep='first')
df_unique

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [19]:
# 6.	Fill missing BillAmount values with the mean bill amount.
mean_bill = df_unique['BillAmount'].mean()
print(mean_bill)
null_value_filled = df_unique['BillAmount'].fillna(mean_bill)
null_value_filled

6233.333333333333

0    5000.000000
1    6233.333333
2    7500.000000
3    6200.000000
4    6233.333333
Name: BillAmount, dtype: float64

In [29]:
df_unique['BillAmount'] = null_value_filled
df_unique

/tmp/ipykernel_2162/125938058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unique['BillAmount'] = null_value_filled

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333

In [30]:
#7.	Merge the billing dataset with patient dataset on PatientID.
merged_df = pd.merge(df_unique,df_original_billing,on='PatientID')
merged_df

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000

In [36]:
# 8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
#Here i am creating my own new patients list because i do not have any other dataframe given
new_patients = {
    'PatientID': [106,107,108],
    'Department':['Neurology','Dermatology','Cardiology'],
    'Doctor':['Dr. John','Dr. Rose','Dr. Smith'],
    'BillAmount':[1000,1500,2000]
}
new_patients_df = pd.DataFrame(new_patients)
new_patients_df

   PatientID   Department     Doctor  BillAmount
0        106    Neurology   Dr. John        1000
1        107  Dermatology   Dr. Rose        1500
2        108   Cardiology  Dr. Smith        2000

In [38]:
concat_df = pd.concat([df_unique,new_patients_df],ignore_index=True)
concat_df
#Without ignore_index=True:
#If df_unique has indices 0-4 and new_patients_df has indices 0-2, the result would have indices 0, 1, 2, 3, 4, 0, 1, 2.

#With ignore_index=True:
#The resulting DataFrame gets a brand new set of indices: 0, 1, 2, 3, 4, 5, 6, 7.

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333
5        106    Neurology   Dr. John  1000.000000
6        107  Dermatology   Dr. Rose  1500.000000
7        108   Cardiology  Dr. Smith  2000.000000

In [ ]:
# 9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [40]:
df_original_billing_final = df_original_billing[['InsuranceCovered', 'FinalAmount']]
new_columns = {
    'InsuranceCovered': [1000,2000,3000],
    'FinalAmount': [1500,2500,3500]
}
new_columns = pd.DataFrame(new_columns)
new_columns

   InsuranceCovered  FinalAmount
0              1000         1500
1              2000         2500
2              3000         3500

In [44]:
concat_columns = pd.concat([df_original_billing_final,new_columns],ignore_index=True)
concat_columns

   InsuranceCovered  FinalAmount
0              2000         3000
1              1500         3500
2              2500         5000
3              3000         3200
4              1000         4000
5              1000         1500
6              2000         2500
7              3000         3500

In [46]:
final_df = pd.concat([concat_df,concat_columns],axis=1)
final_df

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Neurology,Dr. John,1000.000000,1000,1500
6,107,Dermatology,Dr. Rose,1500.000000,2000,2500
7,108,Cardiology,Dr. Smith,2000.000000,3000,3500